org: pavelfadeev
app: my-serverless-experiment
service: my-serverless-experiment

provider:
  name: aws
  region: eu-north-1
  stage: dev

functions:
  serverless-mn-graal:
    package:
      individually: true
      artifact: build/function.zip
    runtime: provided
    memorySize: 256
    handler: not.used.in.provided.runtime
    events:
      - http:
          path: ping/graal
          method: get

  serverless-mn-java:
    package:
      individually: true
      artifact: build/distributions/serverless-playground-0.1.zip
    runtime: java8
    memorySize: 256
    handler: bearmug.lambda.StreamLambdaHandler::handleRequest
    events:
      - http:
          path: ping/java
          method: get

  serverless-nodejs:
    package:
      individually: true
      exclude:
        - ./**
      include:
        - src/main/nodejs/handler.js
    runtime: nodejs10.x
    memorySize: 256
    handler: src/main/nodejs/handler.ping
    events:
      - http:
          path: ping/nodejs
          method: get

