app: mn-ping
service: mn-ping-kotlin

provider:
  name: aws
  region: eu-west-1
  stage: dev

functions:
  mn-graal:
    package:
      individually: true
      artifact: build/function.zip
    runtime: provided
    memorySize: 256
    handler: not.used.in.provided.runtime
    events:
      - http:
          path: ping/graal
          method: get
      - http:
          path: ping/rgraal
          method: get

  mn-kotlin:
    package:
      individually: true
      artifact: build/distributions/mn-ping-kotlin-0.1.zip
    runtime: java8
    memorySize: 256
    handler: bearmug.lambda.StreamLambdaHandler::handleRequest
    events:
      - http:
          path: ping/kotlin
          method: get
      - http:
          path: ping/rkotlin
          method: get
