# Stage 1: Build the native image
FROM oracle/graalvm-ce:19.3.0-java11 as graalvm
RUN gu install native-image
RUN yum install -y libstdc++-static
COPY ./build/libs/mn*-all.jar /home/application/server.jar
WORKDIR /home/application
RUN native-image \
    -H:Class=bearmug.lambda.Application \
    -H:Name=gcp-native-app \
    -H:IncludeResources=application.yml \
    -H:IncludeResources=logback.xml \
    -H:-AllowVMInspection \
    --no-server \
    --no-fallback \
    --initialize-at-build-time=reactor.core.publisher.Flux \
    --initialize-at-build-time=reactor.core.publisher.Mono \
    --static \
    --verbose \
    -cp server.jar \
    -H:ReflectionConfigurationResources=META-INF/native-image/bearmug.lambda/reflection-config.json

# Stage 2: Prepare Server
FROM frolvlad/alpine-glibc
EXPOSE 8080
COPY --from=graalvm /home/application/gcp-native-app .
ENTRYPOINT ["./gcp-native-app"]