# Stage 2: Build the native image
FROM oracle/graalvm-ce:19.2.1 as graalvm
COPY ./build/libs/mn*-all.jar /home/application/server.jar
WORKDIR /home/application
RUN gu install native-image
RUN native-image \
    --no-server \
    --no-fallback \
    --initialize-at-build-time=reactor.core.publisher.Flux \
    --initialize-at-build-time=reactor.core.publisher.Mono \
    -H:Class=bearmug.lambda.Application \
    -H:Name=gcp-native-app \
    -H:IncludeResources=application.yml \
    -H:IncludeResources=logback.xml \
    -H:-AllowVMInspection \
    -cp server.jar

# Stage 3: Prepare Server
FROM frolvlad/alpine-glibc
EXPOSE 8080
COPY --from=graalvm /home/application/gcp-native-app .
ENTRYPOINT ["./gcp-native-app"]