# Stage 1: Build the JAR
FROM gradle:5.1.1-jdk-alpine as gradle
COPY --chown=gradle:gradle . /home/application
WORKDIR /home/application
RUN gradle build --no-daemon

# Stage 2: Build the native image
FROM oracle/graalvm-ce:19.2.1 as graalvm
COPY --from=gradle /home/application/build/libs/serverless-playground-*-all.jar /home/application/server.jar
WORKDIR /home/application
RUN gu install native-image
RUN native-image --no-server --no-fallback -cp server.jar

# Stage 3: Prepare Server
FROM frolvlad/alpine-glibc
EXPOSE 8080
COPY --from=graalvm /home/application/gcp-native-app .
ENTRYPOINT ["./gcp-native-app"]