# Stage 1: Build the native image
FROM oracle/graalvm-ce:19.3.0 as graalvm
RUN yum install zip -y
COPY ./build/libs/mn*-all.jar /home/application/server.jar
WORKDIR /home/application
RUN gu install native-image
RUN native-image \
    --no-server \
    --no-fallback \
    -H:Class=io.micronaut.function.aws.runtime.MicronautLambdaRuntime \
    -H:Name=server \
    -H:IncludeResources=application.yml \
    -H:IncludeResources=logback.xml \
    -H:-AllowVMInspection \
    --initialize-at-build-time=reactor.core.publisher.Flux \
    --initialize-at-build-time=reactor.core.publisher.Mono \
    -cp server.jar
COPY ./bootstrap ./bootstrap
RUN chmod 755 bootstrap
RUN chmod 755 server
RUN zip -j function.zip bootstrap server
EXPOSE 8080
ENTRYPOINT ["/home/application/server"]
